### PR TITLE
Fixes #77, adds widgets to the front page with dummy data in the store

### LINKED ISSUE #77: Home Page Improvement With Dummy Data
##Issue Tracking Form##

I am 

- [ ] filing a bug report
- [x] filing a feature request
- [ ] asking a question about the system

###Contact###

Please stay tuned to this issue! We may contact you through GitHub to ask you more questions about it. If you like, we may also contact you through an alternate form of communication, i.e. email. If this is the case, *transcripts of these communiques may be posted* to the site, in order to allow all contributors to act on the information provided.

*I can be contacted by*: (Please provide instructions for how to contact you)

- [x] I authorize the Omicron Project to publish transcripts of my interactions with the Omicron Project.

###Bug Reports###

Please state the criticality of the bug

- [ ] showstopper, stops the site from functioning
- [ ] critical, prevents a part of the site from functioning in a way that breaks the feature
- [ ] annoying, mis-aligned images, bad CSS, text overflowing its container box

**Provide a description of the bug below**

###Feature Requests###

**Calendar And Carousel For Home Page**

**Description**

The front page needs a [Bootstrap Carousel](https://react-bootstrap.github.io/components.html#carousels), which will cycle automatically between various pieces of data.

The data for the carousel may need to include text and background images.

The page also needs a [calendar](https://react-component.github.io/calendar/) that can show appointment data by day, week, and month.

Key requirements

- [x] Carousel must display any required content in a frame
- [x] Calendar must be selectable by day, week, and month
- [x] Calendar must display appointments at appropriate time

###General Inquiries###

*Ask away! We won't bite!*

My question is: 

(question here)

### PR DESCRIPTION
**Pull request by MichalKononenko**
**Pull Request Form**

If your pull request references a particular issue, please fill out the section "Pull Requests Addressing an Issue".
Otherwise, fill out the "General PRs" section.

**General PRs**

If your pull request does not have an associated issue, please fill out this section.

**Provide a description of the PR below**

**Pull Requests Addressing an Issue**

If your pull request is meant to fix an issue. Please fill out this section

_I am fixing issue number:_ #77
- [x] I included the issue number in the title, preceded by a #

### CODE REVIEW

**Comment by MichalKononenko** [comment]
Hi Deler,

As soon as Heroku builds the review app, can you take a look at this and tell me if you like it?

**Comment by delerla** [comment]
Mike, send me please the link to look at this and tell me if you like it?

**Comment by MichalKononenko** [comment]
Hi Deler

Here's [the link](https://omicronclient-pr-81.herokuapp.com/) to the review app.

**Comment by delerla** [comment]
Michal,
yes, if it is works, mean the change between day, week, etc..

**Comment by MichalKononenko** [comment]
I think I found where the bug is. In the calendar, there is a getter for the date of the form

```javascript
    date["get" + method]()
```

where ```method``` is an argument passed in to the function. It cycles through several dates on the calendar until it gets to the selected date. The selected date defaults to ```new Date(Date.now())```, but this returns the string date instead of the current date. The getter is not defined for a string date, which results in the error.

**Comment by MichalKononenko** [comment]
I think I fixed the bug

**Comment by MichalKononenko** [comment]
Yep. Bug looks fixed. I'm going to go ahead and merge it in now.

**Pull request merged**
